### ISSUE TITLE
[!] Error: experimentalCodeSplitting required to be true

### ISSUE THREAD

**Issue by eugeneross** [alfredosalzillo/rollup-plugin-multi-input#1]
As per [https://github.com/rollup/rollup/releases/tag/v1.0.0](https://github.com/rollup/rollup/releases/tag/v1.0.0), `experimentalCodeSplitting` is enabled by default. Passing the flag, `experimentalCodeSplitting: true,` in `rollup.config.js` throws an error. Not including that flag^ also throws an error.

Error: `[!] Error: experimentalCodeSplitting required to be true`

**Comment by eugeneross** [comment]
Submitted [PR](https://github.com/alfredosalzillo/rollup-plugin-multi-input/pull/2) for the fix.

**Comment by alfredosalzillo** [comment]
Thanks for the fix 👍
