### ISSUE TITLE
Glob negation

### ISSUE THREAD

**Issue by brandonrisell** [alfredosalzillo/rollup-plugin-multi-input#11]
Is there a way to not include certain patterns as part of the glob?

The use case is that I want to include all .js files, but not any that end in `.test.js`.

I tried a couple variations of this `**/(*.js|!*.test.js)`, but I haven't found something that works yet.

**Comment by brandonrisell** [comment]
Figured this out, I went and looked at the under-lying glob package's (fast-glob) docs. This worked:

```js
['src/**/*.js', '!src/**/*.test.js']
```

My use case is to exclude tests from a production rollup build.

**Comment by alfredosalzillo** [comment]
All glob support by fast-glob is supported, maybe I will add more example in the future to cover more sophisticated use cases.
