### ISSUE TITLE
Add an option to allow output relative to input file

### ISSUE THREAD

**Issue by calebdwilliams** [alfredosalzillo/rollup-plugin-multi-input#21]
There should be an option that allows the output file to be located relative to its input. Assume a monorepo of components that need to be rolled up where the desired file structure is 

```
+ packages/
  + package1/
    - package1.js
    - package1.scss
    + lib/
      - package1.output.js
```

Not sure what that syntax should look like, but is this something you'd be interested in adding support for?

FWIW, this is likely related to #3.

**Comment by alfredosalzillo** [comment]
I think is out of scope for this plugin, it can be done using this plugin with one with the ability to modify each output file name.

A naive implementation can be:

```javascript
// rollup-plugin-modify-output-file-name
export default ({
  prepend = '',
} = defaultOptions) => ({
  options({ input }) {
    return {
      input: Object.fromEntries(Object.entries(input).map(([outputFile, inputFIle]) => {
       const { fileName } = /(?<fileName>[^\/]+$)/.exec('assdas/b/asds.txt').groups;
       return [oputFile.replace(fileName, prepend+''+fileName), inputFile];
     })),
    };
  }
})
```

I don't know if a plugin like that already exists.

**Comment by calebdwilliams** [comment]
Yeah, it should be fairly trivial to implement if you added a `transformOutputPath` option to the options object. This just makes sense to me as part of _this_ plugin. If that's something you're interested in adding, I'd be interested in taking a swing at it. If not, feel free to close this issue as `wontfix`.

**Comment by alfredosalzillo** [comment]
I think it can be added, feel free to do that if you want, otherwise I will schedule this.

**Comment by JoyceBabu** [comment]
I would like to send a PR for this. Is this okay?

https://github.com/alfredosalzillo/rollup-plugin-multi-input/compare/master...JoyceBabu:master

**Comment by alfredosalzillo** [comment]
Hi @JoyceBabu, 

you can open the pull request I only have some suggestions:
- `transformOutputPathCallback` type name to `TransformOutputPathFn`
- add some tests of the new option

Thanks!

**Comment by JoyceBabu** [comment]
Thank you.
