### ISSUE TITLE
Multiple output

### ISSUE THREAD

**Issue by ops1ops** [alfredosalzillo/rollup-plugin-multi-input#40]
Hi, as i understand your plugin allows to use multiple file input using regexp, but the problem is that if i use it, rollup creates 1 bundle which includes all files that matched with this regexp. Is there any way to implement feature, which allows to create bundle file for each file matched with regexp? Or maybe i missed it and its already implemented?

**Comment by ops1ops** [comment]
yes but if i use extract option in rollup it creates only 1 css file

**Comment by alfredosalzillo** [comment]
what plugin are you using for css?

**Comment by ops1ops** [comment]
rollup postcss

**Comment by alfredosalzillo** [comment]
can you post the order of the plugins ?

**Comment by ops1ops** [comment]
```  
babel(babelOptions),
resolve(resolveOptions),
commonjs(commonjsOptions),
postcss(postcssOptions),
terser(),
flow(),
json(),
multiInput({ relative: 'src/components/Icon' })
```

**Comment by ops1ops** [comment]
babel(babelOptions),
resolve(resolveOptions),
commonjs(commonjsOptions),
postcss(postcssOptions),
terser(),
flow(),
json(),
multiInput()

**Comment by alfredosalzillo** [comment]
try putting `multiInput()` before `postcss(postcssOptions)`

**Comment by najmsheikh** [comment]
I have a similar requirement as the original poster.  I have my project structured like so:
```
.
├── components
│   ├── BannedComponent.svelte
│   └── TestComponent.svelte
├── index.html
├── package.json
├── rollup.config.js
├── templates
│   ├── AnotherTemplate.svelte
│   └── Default.svelte
└── yarn.lock
```

Then in my rollup config I setup the following 
```javascript
{
  input: ['templates/*.svelte'],
  output: {
    format: 'iife',
    name: 'app',
    dir: 'dist'
  },
}
```

Essentially my intent is that I get a 1:1 matching input:output for every file in `template`. A file in `template` may reference multiple components. And so I'd like it to be a single file that only has referenced code and nothing more. How can I achieve this?
