### ISSUE TITLE
Awesome project - Set up sponsorship

### ISSUE THREAD

**Issue by josephrexme** [alfredosalzillo/rollup-plugin-multi-input#44]
This is an awesome project. You should set up github sponsorship. I know I want to donate a little to this project for the help it gave me. Someone else probably feels the same.

**Comment by alfredosalzillo** [comment]
Thanks @josephrexme!

I'm currently in the whitelist for sponsorship

**Comment by josephrexme** [comment]
I'll keep an eye out for it. Closing this for now
