### ISSUE TITLE
Change the name to rollup-plugin-modular-library

### ISSUE THREAD

**Issue by alfredosalzillo** [alfredosalzillo/rollup-plugin-multi-input#46]
I'm thinking to rename the package to **_rollup-plugin-modular-library_**.

## Motivations

As pointed into this discussion [https://github.com/rollup/awesome/pull/77](https://github.com/rollup/awesome/pull/77), **_rollup-plugin-modular-library_** is a more apt name for the plugin.

**Comment by mcha-dev** [comment]
I found about it by searching for _muli entry_ so the current name is not far off from what it does. 

But if others see _modular output_ as a more fit name/description, then you can change it in the next major release maybe?
