### ISSUE TITLE
cross browser platform support for Windows (You must supply `options.input` to rollup error)

### ISSUE THREAD

**Issue by thescientist13** [alfredosalzillo/rollup-plugin-multi-input#49]
I noticed that while testing my project on a Windows machine, I was getting errors from Rollup due to missing `options.input`.
```sh
$ npm run build

> rollup-multi-input-windows@1.0.0 build C:\Users\IEUser\Workspace\rollup-multi-input-windows
> rollup -c rollup.config.js

inputPath => C:\Users\IEUser\Workspace\rollup-multi-input-windows\src\**\*.js

C:\Users\IEUser\Workspace\rollup-multi-input-windows\src\**\*.js → public...
[!] Error: You must supply options.input to rollup
Error: You must supply options.input to rollup
    at Graph.generateModuleGraph (C:\Users\IEUser\Workspace\rollup-multi-input-windows\node_modules\rollup\dist\shared\rollup.js:18900:19)
    at async Graph.build (C:\Users\IEUser\Workspace\rollup-multi-input-windows\node_modules\rollup\dist\shared\rollup.js:18864:9)
    at async rollupInternal (C:\Users\IEUser\Workspace\rollup-multi-input-windows\node_modules\rollup\dist\shared\rollup.js:19939:9)
    at async build (C:\Users\IEUser\Workspace\rollup-multi-input-windows\node_modules\rollup\dist\bin\rollup:1464:20)
    at async runRollup (C:\Users\IEUser\Workspace\rollup-multi-input-windows\node_modules\rollup\dist\bin\rollup:1645:21)
```

I did some [debugging in this plugin](https://github.com/thescientist13/rollup-multi-input-windows) and was able to distill it down to path separators in conjunction with **fast-glob**'s [own recommendations](https://github.com/mrmlnc/fast-glob#how-to-write-patterns-on-windows).

From there, back in my main project I then received (and resolved) a Rollup issue related to invalid substitutions that came up as a result (which also seems related to reports in this issue: https://github.com/alfredosalzillo/rollup-plugin-multi-input/issues/15#issuecomment-660558275)
```sh
Error: Invalid substitution "..\.greenwood\index" for placeholder "[name]" in "output.entryFileNames" pattern, can be neither absolute nor relative path.
```

----

The linked repo provides a full break down of the issue with minimal reproduction, and solution with a sample of the final code in the _/bak_ folder.  I just forked this repo now and will be working on submitting a PR soon.

Thanks and let me know if you have any thoughts!  👋

**Comment by thescientist13** [comment]
Thanks!  Looking forward to trying this release out later on today.  👍

**Comment by thescientist13** [comment]
Thanks, everything is working!  💯

**Comment by igor-ribeiro** [comment]
It's still happening for me on Windows WSL

```js
export default {
  input: ['src/core/themes/*.theme.ts'],
  output: 'build/themes/*.theme.js',
  plugins: [multi()],
};
````
````
src/core/themes/*.theme.ts → stdout...
[!] Error: You must supply options.input to rollup
````
