### ISSUE TITLE
Relative path not working properly

### ISSUE THREAD

**Issue by fatihaziz** [alfredosalzillo/rollup-plugin-multi-input#58]
Hello,
It seems the relative path not working as expected,

![image](https://user-images.githubusercontent.com/23287658/189513479-a0bf29e3-07ec-43d1-ac6f-096d509abcc5.png)

Why the output of `src/utils/index.ts` become `dist/utils/utils/index.cjs`

sample rollup.config.js
```
import multiInput from 'rollup-plugin-multi-input';
import rollupPluginTypescript from "@rollup/plugin-typescript"

export default {
    input: ['src/index.ts', 'src/utils/index.ts'],
    output: {
      format: 'esm',
      dir: 'dist'
    },
    plugins: [ 
      multiInput({ relative: 'src/' }),
      rollupPluginTypescript()
    ],
};
```

Thank you for your attention.

**Comment by L1lith** [comment]
I'm experiencing this issue as well

**Comment by alfredosalzillo** [comment]
@fatihaziz what version of rollup are you using?
